# Generated by Django 4.0.3 on 2022-03-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='labeled_user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='first_labeled_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='second_labeled_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='dummy_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='first_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='second_status',
            field=models.BooleanField(default=False),
        ),
    ]
