# Generated by Django 4.0.3 on 2022-03-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_rename_user_id_review_labeled_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='labeled_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
