# Generated by Django 4.0.3 on 2022-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_review_labeled_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_number',
            field=models.IntegerField(),
        ),
    ]
