# Generated by Django 4.0.3 on 2022-03-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_review_review_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_Labeled_Data',
            new_name='FirstLabeledData',
        ),
        migrations.RenameModel(
            old_name='Second_Labeled_Data',
            new_name='SecondLabeledData',
        ),
    ]
